jms_serializer:
    property_naming:
        id: "jms_serializer.identical_property_naming_strategy"
    handlers:
        datetime:
            default_format: "Y-m-d\\TH:i:s"
    visitors:
        json_serialization:
            options:
                - JSON_PRETTY_PRINT
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
