version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
    ports:
      - 8001:8000
    volumes:
      - .:/app
    environment:
      XDEBUG_CONFIG: client_host=192.168.1.5 # docker network ip. No OSX usar host.docker.internal, no Ubuntu usar 'ip a' para verificar (em geral 172.17.0.1). Ao alterar o IP, é necessário reconstruir a imagem. Confirme config do xdebug no phpinfo()
      PHP_IDE_CONFIG: serverName=xdebug-docker # phpstorm variavel de ambiente com o nome do server configurado. No VSCODE, manter mesmo valor
      XDEBUG_SESSION: docker
      XDEBUG_TRIGGER: 1
    depends_on:
      - database
      - redis
      - rabbitmq
    networks:
      sapiens_pessoas:
        ipv4_address: 192.168.5.10

  database:
    container_name: oracledb
    image: container-registry.oracle.com/database/free:latest
    hostname: oracledb
    volumes:
      - ./docker/dev/oracle/volume/oradata:/opt/oracle/oradata
      - ./docker/dev/oracle/volume/dbs:/opt/oracle/product/23c/dbhomeFree/dbs
      - ./docker/dev/oracle/dumps:/dumps
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PWD=supp
    networks:
      sapiens_pessoas:
        ipv4_address: 192.168.5.20

  redis:
    container_name: redis_pessoas
    image: eqalpha/keydb:alpine_x86_64_v6.3.3
    hostname: redis
      - "6379:6379"
    ports:
      - 63790:6379
    networks:
      sapiens_pessoas:
        ipv4_address: 192.168.5.30

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      sapiens_pessoas:
        ipv4_address: 192.168.5.12
    environment:
      RABBITMQ_DEFAULT_USER: sapienspessoas
      RABBITMQ_DEFAULT_PASS: sapienspessoas

  pessoas-php-prod:
    container_name: pessoas-php-prod
    environment:
      APP_ENV: "prod"
      APP_DEBUG: 0
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - '8000:8000'
    tty: true
    command: tail -f /dev/null
    networks:
      sapiens_pessoas:
        ipv4_address: 192.168.5.55

networks:
  sapiens_pessoas:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24