<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240518151654 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE ext_log_entries_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_dado_funcional_dados_comple START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_dependente_dados_complement START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_endereco_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_etapas_importacao_sigep_id_ START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_servidor_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_atividade_funcional_ START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_beneficio_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_cargo_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_classe_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_condicao_dependente_ START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_cor_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_curso_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_dado_funcional_id_se START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_dados_bancarios_id_s START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_deficiencia_fisica_i START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_dependente_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_dependente_orgao_id_ START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_documentacao_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_escolaridade_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_estado_civil_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_ferias_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_funcao_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_grau_parentesco_id_s START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_jornada_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_municipio_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_nacionalidade_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_servidor_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_sexo_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_situacao_funcional_i START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_tipo_beneficio_id_se START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_tipo_ocorrencia_apos START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_tipo_ocorrencia_excl START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_tipo_ocorrencia_ingr START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_tipo_ocorrencia_isen START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_tipo_ocorrencia_pss_ START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_titulacao_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_uorg_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_sigepe_upag_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_status_importacao_sigep_id_ START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE sp_telefone_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE TABLE ext_log_entries (id NUMBER(10) NOT NULL, action VARCHAR2(8) NOT NULL, logged_at TIMESTAMP(0) NOT NULL, object_id VARCHAR2(64) DEFAULT NULL NULL, object_class VARCHAR2(191) NOT NULL, version NUMBER(10) NOT NULL, data CLOB DEFAULT NULL NULL, username VARCHAR2(191) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX log_class_lookup_idx ON ext_log_entries (object_class)');
        $this->addSql('CREATE INDEX log_date_lookup_idx ON ext_log_entries (logged_at)');
        $this->addSql('CREATE INDEX log_user_lookup_idx ON ext_log_entries (username)');
        $this->addSql('CREATE INDEX log_version_lookup_idx ON ext_log_entries (object_id, object_class, version)');
        $this->addSql('COMMENT ON COLUMN ext_log_entries.data IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE sp_dado_funcional_dados_complementares (id NUMBER(10) NOT NULL, sigepe_servidor_id NUMBER(10) NOT NULL, rescisao_rais_id NUMBER(10) DEFAULT NULL NULL, situacao_rais_id NUMBER(10) DEFAULT NULL NULL, vinculo_rais_id NUMBER(10) DEFAULT NULL NULL, tipo_admissao_id NUMBER(10) DEFAULT NULL NULL, tipo_salario_id NUMBER(10) DEFAULT NULL NULL, area_atuacao_id NUMBER(10) DEFAULT NULL NULL, lotacao_origem_id NUMBER(10) DEFAULT NULL NULL, lotacao_exercicio_id NUMBER(10) DEFAULT NULL NULL, data_rescisao DATE DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11D02291D17F50A6 ON sp_dado_funcional_dados_complementares (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11D022917E809C0A ON sp_dado_funcional_dados_complementares (sigepe_servidor_id)');
        $this->addSql('CREATE INDEX IDX_11D02291CFC6BFE2 ON sp_dado_funcional_dados_complementares (rescisao_rais_id)');
        $this->addSql('CREATE INDEX IDX_11D02291FD8EE665 ON sp_dado_funcional_dados_complementares (situacao_rais_id)');
        $this->addSql('CREATE INDEX IDX_11D02291FDA2BB07 ON sp_dado_funcional_dados_complementares (vinculo_rais_id)');
        $this->addSql('CREATE INDEX IDX_11D022917B5CBFD6 ON sp_dado_funcional_dados_complementares (tipo_admissao_id)');
        $this->addSql('CREATE INDEX IDX_11D02291A6627106 ON sp_dado_funcional_dados_complementares (tipo_salario_id)');
        $this->addSql('CREATE INDEX IDX_11D02291E6167780 ON sp_dado_funcional_dados_complementares (area_atuacao_id)');
        $this->addSql('CREATE INDEX IDX_11D02291E958F98E ON sp_dado_funcional_dados_complementares (lotacao_origem_id)');
        $this->addSql('CREATE INDEX IDX_11D022914F4E4A77 ON sp_dado_funcional_dados_complementares (lotacao_exercicio_id)');
        $this->addSql('COMMENT ON COLUMN sp_dado_funcional_dados_complementares.rescisao_rais_id IS \'Identificador sequencial e único que especifica um registro na tabela RESCISAO_RAIS.\'');
        $this->addSql('COMMENT ON COLUMN sp_dado_funcional_dados_complementares.situacao_rais_id IS \'Identificador sequencial e único que especifica um registro na tabela SITUACAO_RAIS.\'');
        $this->addSql('COMMENT ON COLUMN sp_dado_funcional_dados_complementares.vinculo_rais_id IS \'Identificador sequencial e único que especifica um registro na tabela VINCULO_RAIS.\'');
        $this->addSql('COMMENT ON COLUMN sp_dado_funcional_dados_complementares.tipo_admissao_id IS \'Identificador sequencial e único que especifica um registro na tabela TIPO _ADMISSAO.\'');
        $this->addSql('COMMENT ON COLUMN sp_dado_funcional_dados_complementares.tipo_salario_id IS \'Identificador sequencial e único que especifica um registro na tabela TIPO_SALARIO.\'');
        $this->addSql('COMMENT ON COLUMN sp_dado_funcional_dados_complementares.area_atuacao_id IS \'Identificador sequencial e único que especifica um registro na tabela AREA_ATUACAO\'');
        $this->addSql('COMMENT ON COLUMN sp_dado_funcional_dados_complementares.lotacao_origem_id IS \'Identificador sequencial e único que especifica um registro na tabela LOTACAO.\'');
        $this->addSql('COMMENT ON COLUMN sp_dado_funcional_dados_complementares.lotacao_exercicio_id IS \'Identificador sequencial e único que especifica um registro na tabela LOTACAO.\'');
        $this->addSql('COMMENT ON COLUMN sp_dado_funcional_dados_complementares.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_dependente_dados_complementares (id NUMBER(10) NOT NULL, sigepe_dependente_id NUMBER(10) NOT NULL, data_nascimento DATE DEFAULT NULL NULL, sexo VARCHAR2(255) DEFAULT NULL NULL, nome_pai VARCHAR2(255) DEFAULT NULL NULL, nome_mae VARCHAR2(255) DEFAULT NULL NULL, data_casamento DATE DEFAULT NULL NULL, cn_data_registro DATE DEFAULT NULL NULL, cn_numero VARCHAR2(255) DEFAULT NULL NULL, cn_livro VARCHAR2(255) DEFAULT NULL NULL, cn_folha VARCHAR2(255) DEFAULT NULL NULL, cn_cartorio VARCHAR2(255) DEFAULT NULL NULL, data_inicio_assistencia DATE DEFAULT NULL NULL, data_fim_assistencia DATE DEFAULT NULL NULL, motivo_fim_assistencia VARCHAR2(255) DEFAULT NULL NULL, observacao VARCHAR2(4000) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A57A7F54D17F50A6 ON sp_dependente_dados_complementares (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A57A7F5481125626 ON sp_dependente_dados_complementares (sigepe_dependente_id)');
        $this->addSql('COMMENT ON COLUMN sp_dependente_dados_complementares.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_endereco (id NUMBER(10) NOT NULL, sigepe_municipio_id NUMBER(10) DEFAULT NULL NULL, tipo_telefone_id NUMBER(10) DEFAULT NULL NULL, sigepe_servidor_id NUMBER(10) NOT NULL, cep VARCHAR2(255) DEFAULT NULL NULL, logradouro VARCHAR2(255) DEFAULT NULL NULL, numero VARCHAR2(255) DEFAULT NULL NULL, complemento VARCHAR2(255) DEFAULT NULL NULL, bairro VARCHAR2(255) DEFAULT NULL NULL, uf VARCHAR2(255) DEFAULT NULL NULL, origem_sigepe NUMBER(1) NOT NULL, observacao VARCHAR2(255) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CA278746D17F50A6 ON sp_endereco (uuid)');
        $this->addSql('CREATE INDEX IDX_CA278746D8641BA ON sp_endereco (sigepe_municipio_id)');
        $this->addSql('CREATE INDEX IDX_CA278746A7F4BB51 ON sp_endereco (tipo_telefone_id)');
        $this->addSql('CREATE INDEX IDX_CA2787467E809C0A ON sp_endereco (sigepe_servidor_id)');
        $this->addSql('COMMENT ON COLUMN sp_endereco.tipo_telefone_id IS \'Identificador sequencial e único que especifica um registro na tabela TIPO_ENDERECO.\'');
        $this->addSql('COMMENT ON COLUMN sp_endereco.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_etapas_importacao_sigep (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B786A56D17F50A6 ON sp_etapas_importacao_sigep (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_etapas_importacao_sigep.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_servidor (id NUMBER(10) NOT NULL, sigepe_servidor_id NUMBER(10) NOT NULL, etnia_id NUMBER(10) DEFAULT NULL NULL, rh_id NUMBER(10) DEFAULT NULL NULL, tipo_sanguineo_id NUMBER(10) DEFAULT NULL NULL, tipo_servidor_id NUMBER(10) DEFAULT NULL NULL, apelido VARCHAR2(255) DEFAULT NULL NULL, data_obito DATE DEFAULT NULL NULL, id_servidor_agu_pessoas VARCHAR2(255) DEFAULT NULL NULL, codigo_servidor_agu_pessoas VARCHAR2(255) DEFAULT NULL NULL, status NUMBER(1) NOT NULL, email_particular VARCHAR2(255) DEFAULT NULL NULL, nome_conjuge VARCHAR2(255) DEFAULT NULL NULL, portador_necessidade_especial NUMBER(1) NOT NULL, nome_necessidade_especial VARCHAR2(255) DEFAULT NULL NULL, doador_orgaos NUMBER(1) NOT NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C9527EB8D17F50A6 ON sp_servidor (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C9527EB87E809C0A ON sp_servidor (sigepe_servidor_id)');
        $this->addSql('CREATE INDEX IDX_C9527EB8594872DC ON sp_servidor (etnia_id)');
        $this->addSql('CREATE INDEX IDX_C9527EB822A2877C ON sp_servidor (rh_id)');
        $this->addSql('CREATE INDEX IDX_C9527EB89ED3A19F ON sp_servidor (tipo_sanguineo_id)');
        $this->addSql('CREATE INDEX IDX_C9527EB874D8C745 ON sp_servidor (tipo_servidor_id)');
        $this->addSql('COMMENT ON COLUMN sp_servidor.etnia_id IS \'Identificador sequencial e único que especifica um registro na tabela ETNIA.\'');
        $this->addSql('COMMENT ON COLUMN sp_servidor.rh_id IS \'Identificador sequencial e único que especifica um registro na tabela RH.\'');
        $this->addSql('COMMENT ON COLUMN sp_servidor.tipo_sanguineo_id IS \'Identificador sequencial e único que especifica um registro na tabela TIPO_SANGUINEO.\'');
        $this->addSql('COMMENT ON COLUMN sp_servidor.tipo_servidor_id IS \'Identificador sequencial e único que especifica um registro na tabela TIPO_SERVIDOR.\'');
        $this->addSql('COMMENT ON COLUMN sp_servidor.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_atividade_funcional (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AFBAEEC4D17F50A6 ON sp_sigepe_atividade_funcional (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_atividade_funcional.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_beneficio (id NUMBER(10) NOT NULL, tipo_id NUMBER(10) DEFAULT NULL NULL, sigepe_dependente_orgao_id NUMBER(10) DEFAULT NULL NULL, data_inicio DATE DEFAULT NULL NULL, data_fim DATE DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2B4487FAD17F50A6 ON sp_sigepe_beneficio (uuid)');
        $this->addSql('CREATE INDEX IDX_2B4487FAA9276E6C ON sp_sigepe_beneficio (tipo_id)');
        $this->addSql('CREATE INDEX IDX_2B4487FA4404A95B ON sp_sigepe_beneficio (sigepe_dependente_orgao_id)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_beneficio.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_cargo (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2C2F2AF4D17F50A6 ON sp_sigepe_cargo (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_cargo.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_classe (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_12420944D17F50A6 ON sp_sigepe_classe (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_classe.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_condicao_dependente (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1156CB8CD17F50A6 ON sp_sigepe_condicao_dependente (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_condicao_dependente.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_cor (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F639C553D17F50A6 ON sp_sigepe_cor (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_cor.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_curso (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DDFA3D69D17F50A6 ON sp_sigepe_curso (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_curso.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_dado_funcional (id NUMBER(10) NOT NULL, orgao_id NUMBER(10) DEFAULT NULL NULL, atividade_funcional_id NUMBER(10) DEFAULT NULL NULL, sigepe_cargo_id NUMBER(10) DEFAULT NULL NULL, sigepe_classe_id NUMBER(10) DEFAULT NULL NULL, sigepe_funcao_id NUMBER(10) DEFAULT NULL NULL, sigepe_jornada_id NUMBER(10) DEFAULT NULL NULL, ocorrencia_aposentadoria_id NUMBER(10) DEFAULT NULL NULL, ocorrencia_exclusao_id NUMBER(10) DEFAULT NULL NULL, ocorrencia_ingresso_orgao_id NUMBER(10) DEFAULT NULL NULL, ocorrencia_ingresso_servico_publico_id NUMBER(10) DEFAULT NULL NULL, ocorrencia_isencao_ir_id NUMBER(10) DEFAULT NULL NULL, ocorrencia_pss_id NUMBER(10) DEFAULT NULL NULL, situacao_funcional_id NUMBER(10) DEFAULT NULL NULL, uorg_exercicio_id NUMBER(10) DEFAULT NULL NULL, uorg_lotacao_id NUMBER(10) DEFAULT NULL NULL, upag_id NUMBER(10) DEFAULT NULL NULL, orgao_origem_id NUMBER(10) DEFAULT NULL NULL, sigepe_servidor_id NUMBER(10) NOT NULL, hash VARCHAR2(255) DEFAULT NULL NULL, matricula VARCHAR2(255) NOT NULL, data_aposentadoria DATE DEFAULT NULL NULL, data_exclusao DATE DEFAULT NULL NULL, data_ingresso_orgao DATE DEFAULT NULL NULL, data_ingresso_servico_publico DATE DEFAULT NULL NULL, data_inicio_isencao_ir DATE DEFAULT NULL NULL, data_fim_isencao_ir DATE DEFAULT NULL NULL, data_inicio_pss DATE DEFAULT NULL NULL, data_fim_pss DATE DEFAULT NULL NULL, codigo_padrao VARCHAR2(255) NOT NULL, vale_transporte_codigo VARCHAR2(255) DEFAULT NULL NULL, vale_transporte_valor VARCHAR2(255) DEFAULT NULL NULL, vale_ar_tipo VARCHAR2(255) DEFAULT NULL NULL, vale_ar_data_inicio DATE DEFAULT NULL NULL, vale_ar_data_fim DATE DEFAULT NULL NULL, chefia_imediata_cpf VARCHAR2(255) DEFAULT NULL NULL, chefia_imediata_email VARCHAR2(255) DEFAULT NULL NULL, data_exercicio_orgao DATE DEFAULT NULL NULL, data_ingresso_funcao DATE DEFAULT NULL NULL, data_ingresso_nova_funcao DATE DEFAULT NULL NULL, percentual_ts VARCHAR2(255) DEFAULT NULL NULL, pontuacao_desempenho VARCHAR2(255) DEFAULT NULL NULL, nivel_cargo_sigla VARCHAR2(255) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B0ABB7FD17F50A6 ON sp_sigepe_dado_funcional (uuid)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7F5CF83614 ON sp_sigepe_dado_funcional (orgao_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7FBD586F55 ON sp_sigepe_dado_funcional (atividade_funcional_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7FA1170BCC ON sp_sigepe_dado_funcional (sigepe_cargo_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7FF014857A ON sp_sigepe_dado_funcional (sigepe_classe_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7F5974BCC1 ON sp_sigepe_dado_funcional (sigepe_funcao_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7FEF9AF87F ON sp_sigepe_dado_funcional (sigepe_jornada_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7F72C03DD5 ON sp_sigepe_dado_funcional (ocorrencia_aposentadoria_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7F8484A14F ON sp_sigepe_dado_funcional (ocorrencia_exclusao_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7F4A6DEF63 ON sp_sigepe_dado_funcional (ocorrencia_ingresso_orgao_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7FC93AE96C ON sp_sigepe_dado_funcional (ocorrencia_ingresso_servico_publico_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7F5A27C27F ON sp_sigepe_dado_funcional (ocorrencia_isencao_ir_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7F4F5B0715 ON sp_sigepe_dado_funcional (ocorrencia_pss_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7FBC3BC6BE ON sp_sigepe_dado_funcional (situacao_funcional_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7F3AA82477 ON sp_sigepe_dado_funcional (uorg_exercicio_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7FC8C8937B ON sp_sigepe_dado_funcional (uorg_lotacao_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7FB3BDA056 ON sp_sigepe_dado_funcional (upag_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7FE6CE94A6 ON sp_sigepe_dado_funcional (orgao_origem_id)');
        $this->addSql('CREATE INDEX IDX_4B0ABB7F7E809C0A ON sp_sigepe_dado_funcional (sigepe_servidor_id)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_dado_funcional.orgao_id IS \'Identificador sequencial e único que especifica um registro na tabela ORGAO.\'');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_dado_funcional.orgao_origem_id IS \'Identificador sequencial e único que especifica um registro na tabela ORGAO.\'');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_dado_funcional.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_dados_bancarios (id NUMBER(10) NOT NULL, agencia_id NUMBER(10) DEFAULT NULL NULL, agencia_outros_pagto_id NUMBER(10) DEFAULT NULL NULL, sigepe_servidor_id NUMBER(10) NOT NULL, matricula VARCHAR2(255) DEFAULT NULL NULL, cod_banco VARCHAR2(255) DEFAULT NULL NULL, nome_banco VARCHAR2(255) DEFAULT NULL NULL, conta_corrente VARCHAR2(255) DEFAULT NULL NULL, cod_banco_outros_pgto VARCHAR2(255) DEFAULT NULL NULL, nome_banco_outros_pgto VARCHAR2(255) DEFAULT NULL NULL, conta_corrente_outros_pgto VARCHAR2(255) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_92933670D17F50A6 ON sp_sigepe_dados_bancarios (uuid)');
        $this->addSql('CREATE INDEX IDX_92933670A6F796BE ON sp_sigepe_dados_bancarios (agencia_id)');
        $this->addSql('CREATE INDEX IDX_92933670AF682B87 ON sp_sigepe_dados_bancarios (agencia_outros_pagto_id)');
        $this->addSql('CREATE INDEX IDX_929336707E809C0A ON sp_sigepe_dados_bancarios (sigepe_servidor_id)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_dados_bancarios.agencia_id IS \'Identificador sequencial e único que especifica um registro na tabela AGENCIA.\'');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_dados_bancarios.agencia_outros_pagto_id IS \'Identificador sequencial e único que especifica um registro na tabela AGENCIA.\'');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_dados_bancarios.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_deficiencia_fisica (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3879A0D0D17F50A6 ON sp_sigepe_deficiencia_fisica (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_deficiencia_fisica.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_dependente (id NUMBER(10) NOT NULL, sigepe_servidor_id NUMBER(10) DEFAULT NULL NULL, cpf VARCHAR2(255) DEFAULT NULL NULL, nome VARCHAR2(255) NOT NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B67B29E3E3E11F0 ON sp_sigepe_dependente (cpf)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B67B29ED17F50A6 ON sp_sigepe_dependente (uuid)');
        $this->addSql('CREATE INDEX IDX_4B67B29E7E809C0A ON sp_sigepe_dependente (sigepe_servidor_id)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_dependente.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_dependente_orgao (id NUMBER(10) NOT NULL, orgao_id NUMBER(10) DEFAULT NULL NULL, sigepe_dependente_id NUMBER(10) DEFAULT NULL NULL, condicao_id NUMBER(10) DEFAULT NULL NULL, parentesco_id NUMBER(10) DEFAULT NULL NULL, matricula VARCHAR2(255) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ED68E95CD17F50A6 ON sp_sigepe_dependente_orgao (uuid)');
        $this->addSql('CREATE INDEX IDX_ED68E95C5CF83614 ON sp_sigepe_dependente_orgao (orgao_id)');
        $this->addSql('CREATE INDEX IDX_ED68E95C81125626 ON sp_sigepe_dependente_orgao (sigepe_dependente_id)');
        $this->addSql('CREATE INDEX IDX_ED68E95C8C043B17 ON sp_sigepe_dependente_orgao (condicao_id)');
        $this->addSql('CREATE INDEX IDX_ED68E95C5BA311FC ON sp_sigepe_dependente_orgao (parentesco_id)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_dependente_orgao.orgao_id IS \'Identificador sequencial e único que especifica um registro na tabela ORGAO.\'');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_dependente_orgao.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_documentacao (id NUMBER(10) NOT NULL, sigepe_servidor_id NUMBER(10) NOT NULL, cpf VARCHAR2(255) DEFAULT NULL NULL, pis_pasep VARCHAR2(255) DEFAULT NULL NULL, passaporte VARCHAR2(255) DEFAULT NULL NULL, ci_numero VARCHAR2(255) DEFAULT NULL NULL, ci_data_expedicao TIMESTAMP(0) DEFAULT NULL NULL, ci_orgao_expedidor VARCHAR2(255) DEFAULT NULL NULL, ci_uf VARCHAR2(255) DEFAULT NULL NULL, cnh_numero VARCHAR2(255) DEFAULT NULL NULL, cnh_categoria VARCHAR2(255) DEFAULT NULL NULL, cnh_data_expedicao TIMESTAMP(0) DEFAULT NULL NULL, cnh_data_primeira_expedicao TIMESTAMP(0) DEFAULT NULL NULL, cnh_validade TIMESTAMP(0) DEFAULT NULL NULL, cnh_registro VARCHAR2(255) DEFAULT NULL NULL, cnh_uf VARCHAR2(255) DEFAULT NULL NULL, te_numero VARCHAR2(255) DEFAULT NULL NULL, te_zona VARCHAR2(255) DEFAULT NULL NULL, te_secao VARCHAR2(255) DEFAULT NULL NULL, te_uf VARCHAR2(255) DEFAULT NULL NULL, te_data_expedicao TIMESTAMP(0) DEFAULT NULL NULL, cm_numero VARCHAR2(255) DEFAULT NULL NULL, cm_data_expedicao TIMESTAMP(0) DEFAULT NULL NULL, cm_orgao_expedidor VARCHAR2(255) DEFAULT NULL NULL, cm_serie VARCHAR2(255) DEFAULT NULL NULL, ct_numero VARCHAR2(255) DEFAULT NULL NULL, ct_serie VARCHAR2(255) DEFAULT NULL NULL, ct_uf VARCHAR2(255) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A34C8235D17F50A6 ON sp_sigepe_documentacao (uuid)');
        $this->addSql('CREATE INDEX IDX_A34C82357E809C0A ON sp_sigepe_documentacao (sigepe_servidor_id)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_documentacao.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_escolaridade (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D892DCE0D17F50A6 ON sp_sigepe_escolaridade (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_escolaridade.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_estado_civil (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_800B5883D17F50A6 ON sp_sigepe_estado_civil (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_estado_civil.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_ferias (id NUMBER(10) NOT NULL, sigepe_servidor_id NUMBER(10) DEFAULT NULL NULL, hash VARCHAR2(255) DEFAULT NULL NULL, ano_exercicio VARCHAR2(255) DEFAULT NULL NULL, data_inicio DATE DEFAULT NULL NULL, data_fim DATE DEFAULT NULL NULL, data_inicio_aquisicao DATE DEFAULT NULL NULL, data_fim_aquisicao DATE DEFAULT NULL NULL, numero_parcela VARCHAR2(255) DEFAULT NULL NULL, qtd_dias NUMBER(10) DEFAULT NULL NULL, parcela_interrompida NUMBER(1) DEFAULT NULL NULL, dias_restantes VARCHAR2(255) DEFAULT NULL NULL, parcela_continuacao_interrupcao NUMBER(1) DEFAULT NULL NULL, data_inicio_ferias_interrompidas DATE DEFAULT NULL NULL, adiantamento_salario_ferias NUMBER(1) DEFAULT NULL NULL, gratificacao_natalina NUMBER(1) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_90A2E1D3D17F50A6 ON sp_sigepe_ferias (uuid)');
        $this->addSql('CREATE INDEX IDX_90A2E1D37E809C0A ON sp_sigepe_ferias (sigepe_servidor_id)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_ferias.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_funcao (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F31B47EFD17F50A6 ON sp_sigepe_funcao (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_funcao.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_grau_parentesco (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E906B965D17F50A6 ON sp_sigepe_grau_parentesco (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_grau_parentesco.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_jornada (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9926AF1D17F50A6 ON sp_sigepe_jornada (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_jornada.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_municipio (id NUMBER(10) NOT NULL, nome VARCHAR2(255) DEFAULT NULL NULL, uf VARCHAR2(255) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_29042B22D17F50A6 ON sp_sigepe_municipio (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_municipio.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_nacionalidade (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_733448D9D17F50A6 ON sp_sigepe_nacionalidade (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_nacionalidade.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_servidor (id NUMBER(10) NOT NULL, sexo_id NUMBER(10) DEFAULT NULL NULL, cor_id NUMBER(10) DEFAULT NULL NULL, deficiencia_fisica_id NUMBER(10) DEFAULT NULL NULL, estado_civil_id NUMBER(10) DEFAULT NULL NULL, nacionalidade_id NUMBER(10) DEFAULT NULL NULL, escolaridade_id NUMBER(10) DEFAULT NULL NULL, cpf VARCHAR2(255) DEFAULT NULL NULL, nome VARCHAR2(255) NOT NULL, email_institucional VARCHAR2(255) DEFAULT NULL NULL, identificacao_unica VARCHAR2(255) DEFAULT NULL NULL, data_nascimento DATE DEFAULT NULL NULL, nome_pai VARCHAR2(255) DEFAULT NULL NULL, nome_mae VARCHAR2(255) DEFAULT NULL NULL, data_chegada_brasil DATE DEFAULT NULL NULL, nome_pais VARCHAR2(255) DEFAULT NULL NULL, grupo_sanguineo VARCHAR2(255) DEFAULT NULL NULL, nome_municipio_nascimento VARCHAR2(255) DEFAULT NULL NULL, nome_u_nascimento VARCHAR2(255) DEFAULT NULL NULL, pis_pasep VARCHAR2(255) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A9903113E3E11F0 ON sp_sigepe_servidor (cpf)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A990311D17F50A6 ON sp_sigepe_servidor (uuid)');
        $this->addSql('CREATE INDEX IDX_6A9903112B32DB58 ON sp_sigepe_servidor (sexo_id)');
        $this->addSql('CREATE INDEX IDX_6A9903117CF648FE ON sp_sigepe_servidor (cor_id)');
        $this->addSql('CREATE INDEX IDX_6A990311265144EC ON sp_sigepe_servidor (deficiencia_fisica_id)');
        $this->addSql('CREATE INDEX IDX_6A99031175376D93 ON sp_sigepe_servidor (estado_civil_id)');
        $this->addSql('CREATE INDEX IDX_6A99031121CE4288 ON sp_sigepe_servidor (nacionalidade_id)');
        $this->addSql('CREATE INDEX IDX_6A990311E99A6E1D ON sp_sigepe_servidor (escolaridade_id)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_servidor.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_servidor_curso (sigepe_servidor_id NUMBER(10) NOT NULL, curso_id NUMBER(10) NOT NULL, PRIMARY KEY(sigepe_servidor_id, curso_id))');
        $this->addSql('CREATE INDEX IDX_4A21E7467E809C0A ON sp_sigepe_servidor_curso (sigepe_servidor_id)');
        $this->addSql('CREATE INDEX IDX_4A21E74687CB4A1F ON sp_sigepe_servidor_curso (curso_id)');
        $this->addSql('CREATE TABLE sp_sigepe_servidor_titulacao (sigepe_servidor_id NUMBER(10) NOT NULL, titulacao_id NUMBER(10) NOT NULL, PRIMARY KEY(sigepe_servidor_id, titulacao_id))');
        $this->addSql('CREATE INDEX IDX_507CC7AE7E809C0A ON sp_sigepe_servidor_titulacao (sigepe_servidor_id)');
        $this->addSql('CREATE INDEX IDX_507CC7AE48645DFA ON sp_sigepe_servidor_titulacao (titulacao_id)');
        $this->addSql('CREATE TABLE sp_sigepe_sexo (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5AFA900CD17F50A6 ON sp_sigepe_sexo (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_sexo.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_situacao_funcional (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_431CB8E1D17F50A6 ON sp_sigepe_situacao_funcional (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_situacao_funcional.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_tipo_beneficio (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7198812BD17F50A6 ON sp_sigepe_tipo_beneficio (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_tipo_beneficio.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_tipo_ocorrencia_aposentadoria (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D110EE4D17F50A6 ON sp_sigepe_tipo_ocorrencia_aposentadoria (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_tipo_ocorrencia_aposentadoria.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_tipo_ocorrencia_exclusao (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3A546E83D17F50A6 ON sp_sigepe_tipo_ocorrencia_exclusao (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_tipo_ocorrencia_exclusao.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_tipo_ocorrencia_ingresso_orgao (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7129B44FD17F50A6 ON sp_sigepe_tipo_ocorrencia_ingresso_orgao (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_tipo_ocorrencia_ingresso_orgao.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_tipo_ocorrencia_ingresso_servico_publico (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CA32F877D17F50A6 ON sp_sigepe_tipo_ocorrencia_ingresso_servico_publico (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_tipo_ocorrencia_ingresso_servico_publico.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_tipo_ocorrencia_isencao_ir (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_33CBBEB8D17F50A6 ON sp_sigepe_tipo_ocorrencia_isencao_ir (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_tipo_ocorrencia_isencao_ir.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_tipo_ocorrencia_pss (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_640BF3E6D17F50A6 ON sp_sigepe_tipo_ocorrencia_pss (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_tipo_ocorrencia_pss.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_titulacao (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2494D213D17F50A6 ON sp_sigepe_titulacao (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_titulacao.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_uorg (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, sigla VARCHAR2(25) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86322ABED17F50A6 ON sp_sigepe_uorg (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_uorg.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_sigepe_upag (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, sigla VARCHAR2(25) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F0A78F61D17F50A6 ON sp_sigepe_upag (uuid)');
        $this->addSql('COMMENT ON COLUMN sp_sigepe_upag.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_status_importacao_sigep (id NUMBER(10) NOT NULL, etapa_importacao_id NUMBER(10) DEFAULT NULL NULL, sigepe_servidor_id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_230743D1D17F50A6 ON sp_status_importacao_sigep (uuid)');
        $this->addSql('CREATE INDEX IDX_230743D161D08DB ON sp_status_importacao_sigep (etapa_importacao_id)');
        $this->addSql('CREATE INDEX IDX_230743D17E809C0A ON sp_status_importacao_sigep (sigepe_servidor_id)');
        $this->addSql('COMMENT ON COLUMN sp_status_importacao_sigep.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('CREATE TABLE sp_telefone (id NUMBER(10) NOT NULL, tipo_telefone_id NUMBER(10) DEFAULT NULL NULL, sigepe_servidor_id NUMBER(10) NOT NULL, ddd VARCHAR2(2) NOT NULL, numero VARCHAR2(30) NOT NULL, observacao VARCHAR2(4000) DEFAULT NULL NULL, origem_sigepe NUMBER(1) NOT NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_13F5B229D17F50A6 ON sp_telefone (uuid)');
        $this->addSql('CREATE INDEX IDX_13F5B229A7F4BB51 ON sp_telefone (tipo_telefone_id)');
        $this->addSql('CREATE INDEX IDX_13F5B2297E809C0A ON sp_telefone (sigepe_servidor_id)');
        $this->addSql('COMMENT ON COLUMN sp_telefone.tipo_telefone_id IS \'Identificador sequencial e único que especifica um registro na tabela TIPO_TELEFONE.\'');
        $this->addSql('COMMENT ON COLUMN sp_telefone.ddd IS \'Número para a Discagem direta a distância (DDD), que é adotado para discagem interurbana através da inserção de prefixos regionais da localidade para onde a pessoa deseja ligar.\'');
        $this->addSql('COMMENT ON COLUMN sp_telefone.numero IS \'Número de contato para o telefone cadastrado de acordo com o tipo de telefone.\'');
        $this->addSql('COMMENT ON COLUMN sp_telefone.observacao IS \'Especificação descritiva para informações a mais relativas ao registro de telefones cadastrados para um servidor ou unidade da AGU.\'');
        $this->addSql('COMMENT ON COLUMN sp_telefone.uuid IS \'(DC2Type:guid)\'');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares ADD CONSTRAINT FK_11D022917E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares ADD CONSTRAINT FK_11D02291CFC6BFE2 FOREIGN KEY (rescisao_rais_id) REFERENCES RESCISAO_RAIS (ID_RESCISAO_RAIS)');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares ADD CONSTRAINT FK_11D02291FD8EE665 FOREIGN KEY (situacao_rais_id) REFERENCES SITUACAO_RAIS (ID_SITUACAO_RAIS)');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares ADD CONSTRAINT FK_11D02291FDA2BB07 FOREIGN KEY (vinculo_rais_id) REFERENCES VINCULO_RAIS (ID_VINCULO_RAIS)');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares ADD CONSTRAINT FK_11D022917B5CBFD6 FOREIGN KEY (tipo_admissao_id) REFERENCES TIPO_ADMISSAO (ID_TIPO_ADMISSAO)');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares ADD CONSTRAINT FK_11D02291A6627106 FOREIGN KEY (tipo_salario_id) REFERENCES TIPO_SALARIO (ID_TIPO_SALARIO)');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares ADD CONSTRAINT FK_11D02291E6167780 FOREIGN KEY (area_atuacao_id) REFERENCES AREA_ATUACAO (ID_AREA_ATUACAO)');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares ADD CONSTRAINT FK_11D02291E958F98E FOREIGN KEY (lotacao_origem_id) REFERENCES LOTACAO (ID_LOTACAO)');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares ADD CONSTRAINT FK_11D022914F4E4A77 FOREIGN KEY (lotacao_exercicio_id) REFERENCES LOTACAO (ID_LOTACAO)');
        $this->addSql('ALTER TABLE sp_dependente_dados_complementares ADD CONSTRAINT FK_A57A7F5481125626 FOREIGN KEY (sigepe_dependente_id) REFERENCES sp_sigepe_dependente (id)');
        $this->addSql('ALTER TABLE sp_endereco ADD CONSTRAINT FK_CA278746D8641BA FOREIGN KEY (sigepe_municipio_id) REFERENCES sp_sigepe_municipio (id)');
        $this->addSql('ALTER TABLE sp_endereco ADD CONSTRAINT FK_CA278746A7F4BB51 FOREIGN KEY (tipo_telefone_id) REFERENCES TIPO_ENDERECO (ID_TIPO_ENDERECO)');
        $this->addSql('ALTER TABLE sp_endereco ADD CONSTRAINT FK_CA2787467E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_servidor ADD CONSTRAINT FK_C9527EB87E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_servidor ADD CONSTRAINT FK_C9527EB8594872DC FOREIGN KEY (etnia_id) REFERENCES ETNIA (ID_ETNIA)');
        $this->addSql('ALTER TABLE sp_servidor ADD CONSTRAINT FK_C9527EB822A2877C FOREIGN KEY (rh_id) REFERENCES RH (ID_RH)');
        $this->addSql('ALTER TABLE sp_servidor ADD CONSTRAINT FK_C9527EB89ED3A19F FOREIGN KEY (tipo_sanguineo_id) REFERENCES TIPO_SANGUINEO (ID_TIPO_SANGUINEO)');
        $this->addSql('ALTER TABLE sp_servidor ADD CONSTRAINT FK_C9527EB874D8C745 FOREIGN KEY (tipo_servidor_id) REFERENCES TIPO_SERVIDOR (ID_TIPO_SERVIDOR)');
        $this->addSql('ALTER TABLE sp_sigepe_beneficio ADD CONSTRAINT FK_2B4487FAA9276E6C FOREIGN KEY (tipo_id) REFERENCES sp_sigepe_tipo_beneficio (id)');
        $this->addSql('ALTER TABLE sp_sigepe_beneficio ADD CONSTRAINT FK_2B4487FA4404A95B FOREIGN KEY (sigepe_dependente_orgao_id) REFERENCES sp_sigepe_dependente_orgao (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7F5CF83614 FOREIGN KEY (orgao_id) REFERENCES ORGAO (ID_ORGAO)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7FBD586F55 FOREIGN KEY (atividade_funcional_id) REFERENCES sp_sigepe_atividade_funcional (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7FA1170BCC FOREIGN KEY (sigepe_cargo_id) REFERENCES sp_sigepe_cargo (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7FF014857A FOREIGN KEY (sigepe_classe_id) REFERENCES sp_sigepe_classe (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7F5974BCC1 FOREIGN KEY (sigepe_funcao_id) REFERENCES sp_sigepe_funcao (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7FEF9AF87F FOREIGN KEY (sigepe_jornada_id) REFERENCES sp_sigepe_jornada (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7F72C03DD5 FOREIGN KEY (ocorrencia_aposentadoria_id) REFERENCES sp_sigepe_tipo_ocorrencia_aposentadoria (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7F8484A14F FOREIGN KEY (ocorrencia_exclusao_id) REFERENCES sp_sigepe_tipo_ocorrencia_exclusao (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7F4A6DEF63 FOREIGN KEY (ocorrencia_ingresso_orgao_id) REFERENCES sp_sigepe_tipo_ocorrencia_ingresso_orgao (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7FC93AE96C FOREIGN KEY (ocorrencia_ingresso_servico_publico_id) REFERENCES sp_sigepe_tipo_ocorrencia_ingresso_servico_publico (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7F5A27C27F FOREIGN KEY (ocorrencia_isencao_ir_id) REFERENCES sp_sigepe_tipo_ocorrencia_isencao_ir (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7F4F5B0715 FOREIGN KEY (ocorrencia_pss_id) REFERENCES sp_sigepe_tipo_ocorrencia_pss (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7FBC3BC6BE FOREIGN KEY (situacao_funcional_id) REFERENCES sp_sigepe_situacao_funcional (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7F3AA82477 FOREIGN KEY (uorg_exercicio_id) REFERENCES sp_sigepe_uorg (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7FC8C8937B FOREIGN KEY (uorg_lotacao_id) REFERENCES sp_sigepe_uorg (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7FB3BDA056 FOREIGN KEY (upag_id) REFERENCES sp_sigepe_upag (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7FE6CE94A6 FOREIGN KEY (orgao_origem_id) REFERENCES ORGAO (ID_ORGAO)');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional ADD CONSTRAINT FK_4B0ABB7F7E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dados_bancarios ADD CONSTRAINT FK_92933670A6F796BE FOREIGN KEY (agencia_id) REFERENCES AGENCIA (ID_AGENCIA)');
        $this->addSql('ALTER TABLE sp_sigepe_dados_bancarios ADD CONSTRAINT FK_92933670AF682B87 FOREIGN KEY (agencia_outros_pagto_id) REFERENCES AGENCIA (ID_AGENCIA)');
        $this->addSql('ALTER TABLE sp_sigepe_dados_bancarios ADD CONSTRAINT FK_929336707E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dependente ADD CONSTRAINT FK_4B67B29E7E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dependente_orgao ADD CONSTRAINT FK_ED68E95C5CF83614 FOREIGN KEY (orgao_id) REFERENCES ORGAO (ID_ORGAO)');
        $this->addSql('ALTER TABLE sp_sigepe_dependente_orgao ADD CONSTRAINT FK_ED68E95C81125626 FOREIGN KEY (sigepe_dependente_id) REFERENCES sp_sigepe_dependente (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dependente_orgao ADD CONSTRAINT FK_ED68E95C8C043B17 FOREIGN KEY (condicao_id) REFERENCES sp_sigepe_condicao_dependente (id)');
        $this->addSql('ALTER TABLE sp_sigepe_dependente_orgao ADD CONSTRAINT FK_ED68E95C5BA311FC FOREIGN KEY (parentesco_id) REFERENCES sp_sigepe_grau_parentesco (id)');
        $this->addSql('ALTER TABLE sp_sigepe_documentacao ADD CONSTRAINT FK_A34C82357E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_sigepe_ferias ADD CONSTRAINT FK_90A2E1D37E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor ADD CONSTRAINT FK_6A9903112B32DB58 FOREIGN KEY (sexo_id) REFERENCES sp_sigepe_sexo (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor ADD CONSTRAINT FK_6A9903117CF648FE FOREIGN KEY (cor_id) REFERENCES sp_sigepe_cor (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor ADD CONSTRAINT FK_6A990311265144EC FOREIGN KEY (deficiencia_fisica_id) REFERENCES sp_sigepe_deficiencia_fisica (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor ADD CONSTRAINT FK_6A99031175376D93 FOREIGN KEY (estado_civil_id) REFERENCES sp_sigepe_estado_civil (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor ADD CONSTRAINT FK_6A99031121CE4288 FOREIGN KEY (nacionalidade_id) REFERENCES sp_sigepe_nacionalidade (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor ADD CONSTRAINT FK_6A990311E99A6E1D FOREIGN KEY (escolaridade_id) REFERENCES sp_sigepe_escolaridade (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor_curso ADD CONSTRAINT FK_4A21E7467E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor_curso ADD CONSTRAINT FK_4A21E74687CB4A1F FOREIGN KEY (curso_id) REFERENCES sp_sigepe_curso (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor_titulacao ADD CONSTRAINT FK_507CC7AE7E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_sigepe_servidor_titulacao ADD CONSTRAINT FK_507CC7AE48645DFA FOREIGN KEY (titulacao_id) REFERENCES sp_sigepe_titulacao (id)');
        $this->addSql('ALTER TABLE sp_status_importacao_sigep ADD CONSTRAINT FK_230743D161D08DB FOREIGN KEY (etapa_importacao_id) REFERENCES sp_etapas_importacao_sigep (id)');
        $this->addSql('ALTER TABLE sp_status_importacao_sigep ADD CONSTRAINT FK_230743D17E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
        $this->addSql('ALTER TABLE sp_telefone ADD CONSTRAINT FK_13F5B229A7F4BB51 FOREIGN KEY (tipo_telefone_id) REFERENCES TIPO_TELEFONE (ID_TIPO_TELEFONE)');
        $this->addSql('ALTER TABLE sp_telefone ADD CONSTRAINT FK_13F5B2297E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP SEQUENCE ext_log_entries_id_seq');
        $this->addSql('DROP SEQUENCE sp_dado_funcional_dados_comple');
        $this->addSql('DROP SEQUENCE sp_dependente_dados_complement');
        $this->addSql('DROP SEQUENCE sp_endereco_id_seq');
        $this->addSql('DROP SEQUENCE sp_etapas_importacao_sigep_id_');
        $this->addSql('DROP SEQUENCE sp_servidor_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_atividade_funcional_');
        $this->addSql('DROP SEQUENCE sp_sigepe_beneficio_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_cargo_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_classe_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_condicao_dependente_');
        $this->addSql('DROP SEQUENCE sp_sigepe_cor_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_curso_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_dado_funcional_id_se');
        $this->addSql('DROP SEQUENCE sp_sigepe_dados_bancarios_id_s');
        $this->addSql('DROP SEQUENCE sp_sigepe_deficiencia_fisica_i');
        $this->addSql('DROP SEQUENCE sp_sigepe_dependente_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_dependente_orgao_id_');
        $this->addSql('DROP SEQUENCE sp_sigepe_documentacao_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_escolaridade_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_estado_civil_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_ferias_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_funcao_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_grau_parentesco_id_s');
        $this->addSql('DROP SEQUENCE sp_sigepe_jornada_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_municipio_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_nacionalidade_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_servidor_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_sexo_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_situacao_funcional_i');
        $this->addSql('DROP SEQUENCE sp_sigepe_tipo_beneficio_id_se');
        $this->addSql('DROP SEQUENCE sp_sigepe_tipo_ocorrencia_apos');
        $this->addSql('DROP SEQUENCE sp_sigepe_tipo_ocorrencia_excl');
        $this->addSql('DROP SEQUENCE sp_sigepe_tipo_ocorrencia_ingr');
        $this->addSql('DROP SEQUENCE sp_sigepe_tipo_ocorrencia_isen');
        $this->addSql('DROP SEQUENCE sp_sigepe_tipo_ocorrencia_pss_');
        $this->addSql('DROP SEQUENCE sp_sigepe_titulacao_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_uorg_id_seq');
        $this->addSql('DROP SEQUENCE sp_sigepe_upag_id_seq');
        $this->addSql('DROP SEQUENCE sp_status_importacao_sigep_id_');
        $this->addSql('DROP SEQUENCE sp_telefone_id_seq');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares DROP CONSTRAINT FK_11D022917E809C0A');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares DROP CONSTRAINT FK_11D02291CFC6BFE2');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares DROP CONSTRAINT FK_11D02291FD8EE665');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares DROP CONSTRAINT FK_11D02291FDA2BB07');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares DROP CONSTRAINT FK_11D022917B5CBFD6');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares DROP CONSTRAINT FK_11D02291A6627106');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares DROP CONSTRAINT FK_11D02291E6167780');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares DROP CONSTRAINT FK_11D02291E958F98E');
        $this->addSql('ALTER TABLE sp_dado_funcional_dados_complementares DROP CONSTRAINT FK_11D022914F4E4A77');
        $this->addSql('ALTER TABLE sp_dependente_dados_complementares DROP CONSTRAINT FK_A57A7F5481125626');
        $this->addSql('ALTER TABLE sp_endereco DROP CONSTRAINT FK_CA278746D8641BA');
        $this->addSql('ALTER TABLE sp_endereco DROP CONSTRAINT FK_CA278746A7F4BB51');
        $this->addSql('ALTER TABLE sp_endereco DROP CONSTRAINT FK_CA2787467E809C0A');
        $this->addSql('ALTER TABLE sp_servidor DROP CONSTRAINT FK_C9527EB87E809C0A');
        $this->addSql('ALTER TABLE sp_servidor DROP CONSTRAINT FK_C9527EB8594872DC');
        $this->addSql('ALTER TABLE sp_servidor DROP CONSTRAINT FK_C9527EB822A2877C');
        $this->addSql('ALTER TABLE sp_servidor DROP CONSTRAINT FK_C9527EB89ED3A19F');
        $this->addSql('ALTER TABLE sp_servidor DROP CONSTRAINT FK_C9527EB874D8C745');
        $this->addSql('ALTER TABLE sp_sigepe_beneficio DROP CONSTRAINT FK_2B4487FAA9276E6C');
        $this->addSql('ALTER TABLE sp_sigepe_beneficio DROP CONSTRAINT FK_2B4487FA4404A95B');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7F5CF83614');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7FBD586F55');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7FA1170BCC');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7FF014857A');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7F5974BCC1');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7FEF9AF87F');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7F72C03DD5');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7F8484A14F');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7F4A6DEF63');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7FC93AE96C');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7F5A27C27F');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7F4F5B0715');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7FBC3BC6BE');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7F3AA82477');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7FC8C8937B');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7FB3BDA056');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7FE6CE94A6');
        $this->addSql('ALTER TABLE sp_sigepe_dado_funcional DROP CONSTRAINT FK_4B0ABB7F7E809C0A');
        $this->addSql('ALTER TABLE sp_sigepe_dados_bancarios DROP CONSTRAINT FK_92933670A6F796BE');
        $this->addSql('ALTER TABLE sp_sigepe_dados_bancarios DROP CONSTRAINT FK_92933670AF682B87');
        $this->addSql('ALTER TABLE sp_sigepe_dados_bancarios DROP CONSTRAINT FK_929336707E809C0A');
        $this->addSql('ALTER TABLE sp_sigepe_dependente DROP CONSTRAINT FK_4B67B29E7E809C0A');
        $this->addSql('ALTER TABLE sp_sigepe_dependente_orgao DROP CONSTRAINT FK_ED68E95C5CF83614');
        $this->addSql('ALTER TABLE sp_sigepe_dependente_orgao DROP CONSTRAINT FK_ED68E95C81125626');
        $this->addSql('ALTER TABLE sp_sigepe_dependente_orgao DROP CONSTRAINT FK_ED68E95C8C043B17');
        $this->addSql('ALTER TABLE sp_sigepe_dependente_orgao DROP CONSTRAINT FK_ED68E95C5BA311FC');
        $this->addSql('ALTER TABLE sp_sigepe_documentacao DROP CONSTRAINT FK_A34C82357E809C0A');
        $this->addSql('ALTER TABLE sp_sigepe_ferias DROP CONSTRAINT FK_90A2E1D37E809C0A');
        $this->addSql('ALTER TABLE sp_sigepe_servidor DROP CONSTRAINT FK_6A9903112B32DB58');
        $this->addSql('ALTER TABLE sp_sigepe_servidor DROP CONSTRAINT FK_6A9903117CF648FE');
        $this->addSql('ALTER TABLE sp_sigepe_servidor DROP CONSTRAINT FK_6A990311265144EC');
        $this->addSql('ALTER TABLE sp_sigepe_servidor DROP CONSTRAINT FK_6A99031175376D93');
        $this->addSql('ALTER TABLE sp_sigepe_servidor DROP CONSTRAINT FK_6A99031121CE4288');
        $this->addSql('ALTER TABLE sp_sigepe_servidor DROP CONSTRAINT FK_6A990311E99A6E1D');
        $this->addSql('ALTER TABLE sp_sigepe_servidor_curso DROP CONSTRAINT FK_4A21E7467E809C0A');
        $this->addSql('ALTER TABLE sp_sigepe_servidor_curso DROP CONSTRAINT FK_4A21E74687CB4A1F');
        $this->addSql('ALTER TABLE sp_sigepe_servidor_titulacao DROP CONSTRAINT FK_507CC7AE7E809C0A');
        $this->addSql('ALTER TABLE sp_sigepe_servidor_titulacao DROP CONSTRAINT FK_507CC7AE48645DFA');
        $this->addSql('ALTER TABLE sp_status_importacao_sigep DROP CONSTRAINT FK_230743D161D08DB');
        $this->addSql('ALTER TABLE sp_status_importacao_sigep DROP CONSTRAINT FK_230743D17E809C0A');
        $this->addSql('ALTER TABLE sp_telefone DROP CONSTRAINT FK_13F5B229A7F4BB51');
        $this->addSql('ALTER TABLE sp_telefone DROP CONSTRAINT FK_13F5B2297E809C0A');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE sp_dado_funcional_dados_complementares');
        $this->addSql('DROP TABLE sp_dependente_dados_complementares');
        $this->addSql('DROP TABLE sp_endereco');
        $this->addSql('DROP TABLE sp_etapas_importacao_sigep');
        $this->addSql('DROP TABLE sp_servidor');
        $this->addSql('DROP TABLE sp_sigepe_atividade_funcional');
        $this->addSql('DROP TABLE sp_sigepe_beneficio');
        $this->addSql('DROP TABLE sp_sigepe_cargo');
        $this->addSql('DROP TABLE sp_sigepe_classe');
        $this->addSql('DROP TABLE sp_sigepe_condicao_dependente');
        $this->addSql('DROP TABLE sp_sigepe_cor');
        $this->addSql('DROP TABLE sp_sigepe_curso');
        $this->addSql('DROP TABLE sp_sigepe_dado_funcional');
        $this->addSql('DROP TABLE sp_sigepe_dados_bancarios');
        $this->addSql('DROP TABLE sp_sigepe_deficiencia_fisica');
        $this->addSql('DROP TABLE sp_sigepe_dependente');
        $this->addSql('DROP TABLE sp_sigepe_dependente_orgao');
        $this->addSql('DROP TABLE sp_sigepe_documentacao');
        $this->addSql('DROP TABLE sp_sigepe_escolaridade');
        $this->addSql('DROP TABLE sp_sigepe_estado_civil');
        $this->addSql('DROP TABLE sp_sigepe_ferias');
        $this->addSql('DROP TABLE sp_sigepe_funcao');
        $this->addSql('DROP TABLE sp_sigepe_grau_parentesco');
        $this->addSql('DROP TABLE sp_sigepe_jornada');
        $this->addSql('DROP TABLE sp_sigepe_municipio');
        $this->addSql('DROP TABLE sp_sigepe_nacionalidade');
        $this->addSql('DROP TABLE sp_sigepe_servidor');
        $this->addSql('DROP TABLE sp_sigepe_servidor_curso');
        $this->addSql('DROP TABLE sp_sigepe_servidor_titulacao');
        $this->addSql('DROP TABLE sp_sigepe_sexo');
        $this->addSql('DROP TABLE sp_sigepe_situacao_funcional');
        $this->addSql('DROP TABLE sp_sigepe_tipo_beneficio');
        $this->addSql('DROP TABLE sp_sigepe_tipo_ocorrencia_aposentadoria');
        $this->addSql('DROP TABLE sp_sigepe_tipo_ocorrencia_exclusao');
        $this->addSql('DROP TABLE sp_sigepe_tipo_ocorrencia_ingresso_orgao');
        $this->addSql('DROP TABLE sp_sigepe_tipo_ocorrencia_ingresso_servico_publico');
        $this->addSql('DROP TABLE sp_sigepe_tipo_ocorrencia_isencao_ir');
        $this->addSql('DROP TABLE sp_sigepe_tipo_ocorrencia_pss');
        $this->addSql('DROP TABLE sp_sigepe_titulacao');
        $this->addSql('DROP TABLE sp_sigepe_uorg');
        $this->addSql('DROP TABLE sp_sigepe_upag');
        $this->addSql('DROP TABLE sp_status_importacao_sigep');
        $this->addSql('DROP TABLE sp_telefone');
    }
}
