monolog:
    handlers:
        main:
            type: filter
            min_level: error
            handler: rotating_file
        rotating_file:
            type: rotating_file
            path: "/var/www/html/var/log/prod.log"
            max_files: 3
            level: debug
