/* MIGRATE CRIACAO TABELAS SPTIPOCERTIDAO e SPCERTIDAO 29/08/2024 */
-- Início da transação
BEGIN

        EXECUTE IMMEDIATE 'CREATE SEQUENCE sp_certidao_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE sp_tipo_certidao_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1';
        EXECUTE IMMEDIATE 'CREATE TABLE sp_certidao (id NUMBER(10) NOT NULL, tipo_id NUMBER(10) DEFAULT NULL NULL, sp_servidor_id NUMBER(10) NOT NULL, nup_numero VARCHAR2(255) DEFAULT NULL NULL, data_solicitacao DATE DEFAULT NULL NULL, justificativa_solicitacao VARCHAR2(4000) DEFAULT NULL NULL, info_adicionais CLOB DEFAULT NULL NULL, data_avaliacao DATE DEFAULT NULL NULL, resultado_avaliacao VARCHAR2(4000) DEFAULT NULL NULL, status VARCHAR2(3) DEFAULT NULL NULL, nup_data_criacao_tarefa DATE DEFAULT NULL NULL, nup_data_anexo_certidao DATE DEFAULT NULL NULL, nup_log CLOB DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))';
       	EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UNIQ_633549A4D17F50A6 ON sp_certidao (uuid)';
      	EXECUTE IMMEDIATE 'CREATE INDEX IDX_633549A4A9276E6C ON sp_certidao (tipo_id)';
     	EXECUTE IMMEDIATE 'CREATE INDEX IDX_633549A47E809C0A ON sp_certidao (sp_servidor_id)';
    	EXECUTE IMMEDIATE 'CREATE TABLE sp_tipo_certidao (id NUMBER(10) NOT NULL, ativo NUMBER(1) NOT NULL, requer_nup NUMBER(1) NOT NULL, uuid CHAR(36) NOT NULL, nome VARCHAR2(255) NOT NULL, descricao VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))';
   		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UNIQ_D3637122D17F50A6 ON sp_tipo_certidao (uuid)';
   		EXECUTE IMMEDIATE 'ALTER TABLE sp_certidao ADD CONSTRAINT FK_633549A4A9276E6C FOREIGN KEY (tipo_id) REFERENCES sp_tipo_certidao (id)';
   		EXECUTE IMMEDIATE 'ALTER TABLE sp_certidao ADD CONSTRAINT FK_633549A47E809C0A FOREIGN KEY (sp_servidor_id) REFERENCES sp_servidor (id)';
    -- Commit da transação
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        -- Em caso de erro, realizar rollback
        ROLLBACK;
        -- Lançar a exceção para identificar o erro
        RAISE;
END;