ALTER TABLE AGU_RH.SP_ENDERECO RENAME COLUMN TIPO_TELEFONE_ID TO TIPO_ENDERECO_ID;
ALTER TABLE AGU_RH.SERVIDOR ADD DT_IMPORTACAO_SP DATE NULL;
COMMENT ON COLUMN AGU_RH.SERVIDOR.DT_IMPORTACAO_SP IS 'Data que foi importado para o Sapiens Pessoas';
ALTER TABLE AGU_RH.SERVIDOR ADD MSG_FALHA_IMPORTACAO_SP VARCHAR2(4000) NULL;
COMMENT ON COLUMN AGU_RH.SERVIDOR.MSG_FALHA_IMPORTACAO_SP IS 'Mensagem retornada em caso de falha na importação para o Sapiens Pessoas';