CREATE SEQUENCE sp_sigepe_afastamento_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE sp_sigepe_tipo_diploma_afasta_ START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE sp_sigepe_tipo_ocor_afasta_id_ START WITH 1 MINVALUE 1 INCREMENT BY 1;

CREATE TABLE sp_sigepe_afastamento (id NUMBER(10) NOT NULL, sigepe_servidor_id NUMBER(10) DEFAULT NULL NULL, tipo_ocorrencia_id NUMBER(10) DEFAULT NULL NULL, tipo_diploma_id NUMBER(10) DEFAULT NULL NULL, hash VARCHAR2(255) DEFAULT NULL NULL, matricula VARCHAR2(255) DEFAULT NULL NULL, data_inicio DATE DEFAULT NULL NULL, data_fim DATE DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX UNIQ_B586A82FD17F50A6 ON sp_sigepe_afastamento (uuid);
CREATE INDEX IDX_B586A82F7E809C0A ON sp_sigepe_afastamento (sigepe_servidor_id);
CREATE INDEX IDX_B586A82FD51705AC ON sp_sigepe_afastamento (tipo_ocorrencia_id);
CREATE INDEX IDX_B586A82F381CCC9D ON sp_sigepe_afastamento (tipo_diploma_id);
CREATE TABLE sp_sigepe_tipo_diploma_afasta (id NUMBER(10) NOT NULL, numero_diploma VARCHAR2(255) DEFAULT NULL NULL, data_publicacao DATE DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, NOME CHAR(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX UNIQ_BC32CE9ED17F50A6 ON sp_sigepe_tipo_diploma_afasta (uuid);
CREATE TABLE sp_sigepe_tipo_ocor_afasta (id NUMBER(10) NOT NULL, uuid CHAR(36) NOT NULL, codigo_sigepe VARCHAR2(255) NOT NULL, NOME CHAR(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX UNIQ_B2BF4ED2D17F50A6 ON sp_sigepe_tipo_ocor_afasta (uuid);

ALTER TABLE sp_sigepe_afastamento ADD CONSTRAINT FK_B586A82F7E809C0A FOREIGN KEY (sigepe_servidor_id) REFERENCES sp_sigepe_servidor (id);
ALTER TABLE sp_sigepe_afastamento ADD CONSTRAINT FK_B586A82FD51705AC FOREIGN KEY (tipo_ocorrencia_id) REFERENCES sp_sigepe_tipo_ocor_afasta (id);
ALTER TABLE sp_sigepe_afastamento ADD CONSTRAINT FK_B586A82F381CCC9D FOREIGN KEY (tipo_diploma_id) REFERENCES sp_sigepe_tipo_diploma_afasta (id);

INSERT INTO SP_ETAPAS_IMPORTACAO_SIGEP (ID, UUID, CODIGO, NOME) VALUES (9, 'cf209056-a435-4c5c-a4ec-8a6ae7709812', 'AF', 'Afastamentos');
INSERT INTO SP_ETAPAS_IMPORTACAO_SIGEP (ID, UUID, CODIGO, NOME) VALUES (10, 'cf209056-a435-4c5c-a4ec-8a6ae7709813', 'AF_HIS', 'Afastamentos Histórico');
INSERT INTO SP_ETAPAS_IMPORTACAO_SIGEP (ID, UUID, CODIGO, NOME) VALUES (11, 'cf209056-a435-4c5c-a4ec-8a6ae7709814', 'FER_HIS', 'Férias Histórico');
