<?php

namespace AguPessoas\Backend\Api\V2\Enums;

enum Certidao: string
{
    case DECLARACAO_LICENCA_CAPACITACAO = 'DLC';
    case DECLARACAO_LICENCA_POS_GRADUACAO_EXTERIOR = 'DLPGE';
    case DECLARACAO_JUNTO_INSS = 'DJI';
    case DECLARACAO_NAO_RECEBIMENTO_ASSISTENCIA_SAUDE_SUPLEMENTAR = 'DNRASS';
    case DECLARACAO_SIMPLES_BASE = 'DSB';
}
